export const DATAOPPORTUNITES=[
         {  id:1,
            title:'Technical Services',
            sub_title:'A process that involves everything from identifying, attracting, shortlisting, interviewing, selecting, hiring',
            slug:'technical-services',
            image:'../images/secteur-1.jpg',
            description:"The CEO's role in raising a company's corporate IQ is to establish an atmosphere that promotes knowledge sharing and collaboration.",
            description_2:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt utlabore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus com",
            list:['Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi']
          },
          { id:2,
            title:'executive search',
            sub_title:'A process that involves everything from identifying, attracting, shortlisting, interviewing, selecting, hiring',
            slug:'executive-search',
            image:'../images/secteur-2.jpg',
            description:"The CEO's role in raising a company's corporate IQ is to establish an atmosphere that promotes knowledge sharing and collaboration.",
            description_2:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt utlabore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus com",
            list:['s Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi']
          },
          {  id:3,
            title:'Monpower supply',
            sub_title:'A process that involves everything from identifying, attracting, shortlisting, interviewing, selecting, hiring',
            slug:'monpower-supply',
            image:'../images/secteur-2.jpg',
            description:"The CEO's role in raising a company's corporate IQ is to establish an atmosphere that promotes knowledge sharing and collaboration.",
            description_2:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt utlabore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus com",
            list:['Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi']
          },
          { id:4,
            title:'retrained search',
            sub_title:'A process that involves everything from identifying, attracting, shortlisting, interviewing, selecting, hiring',
            slug:'retrained-search-2',
            image:'../images/secteur-1.jpg',
            description:"The CEO's role in raising a company's corporate IQ is to establish an atmosphere that promotes knowledge sharing and collaboration.",
            description_2:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt utlabore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus com",
            list:['Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi']
          },
          { id:5,
            title:'Technical Services',
            sub_title:'A process that involves everything from identifying, attracting, shortlisting, interviewing, selecting, hiring',
            slug:'technical-services-2',
            image:'../images/secteur-2.jpg',
            description:"The CEO's role in raising a company's corporate IQ is to establish an atmosphere that promotes knowledge sharing and collaboration.",
            description_2:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt utlabore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus com",
            list:['Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi']
          },
          { id:6,
            title:'Fort acquisition',
            sub_title:'A process that involves everything from identifying, attracting, shortlisting, interviewing, selecting, hiring',
            slug:'fort-acquisition-2',
            image:'../images/secteur-2.jpg',
            description:"The CEO's role in raising a company's corporate IQ is to establish an atmosphere that promotes knowledge sharing and collaboration.",
            description_2:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt utlabore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus com",
            list:['Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi']
          },
          {  id:7,
            title:'retrained search',
            sub_title:'A process that involves everything from identifying, attracting, shortlisting, interviewing, selecting, hiring',
            slug:'retrained-searc-2',
            image:'../images/secteur-1.jpg',
            description:"The CEO's role in raising a company's corporate IQ is to establish an atmosphere that promotes knowledge sharing and collaboration.",
            description_2:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt utlabore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus com",
            list:['Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi']
          },
          { id:8,
            title:'Monpower supply',
            sub_title:'A process that involves everything from identifying, attracting, shortlisting, interviewing, selecting, hiring',
            slug:'monpower-supply-2',
            image:'../images/secteur-2.jpg',
            description:"The CEO's role in raising a company's corporate IQ is to establish an atmosphere that promotes knowledge sharing and collaboration.",
            description_2:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt utlabore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus com",
            list:['Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi','Lorem ipsum dolor sit amet, consectetur adipi']
          }
]
